name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: ututono/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Automatic github token
          GH_TOKEN: ${{ github.token }}
          # Manual Commit messages - write your own messages here
          COMMIT_MESSAGE: "Automated Coding Activity Update :alien:"
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 5
